export const es_ar = {
  system: {
    name: "Admin-Auth",
  },
  common: {
    welcome: "Bienvenido",
    appName: "Admin Auth",
    messageWelcome: "Bienvenido al administrador de autenticación",
    actions: {
      detail: "Detalles",
      edit: "Editar",
      delete: "Eliminar",
      view: "Ver",
      cancel: "Cancelar",
      save: "Guardar",
      create: "Crear",
      confirm: "Confirmar",
      add: "Agregar",
      new: "Nuevo",
      remove: "Remover",
      accept: "Aceptar",
      reject: "Rechazar",
      enter: "Ingresar",
      open: "Abrir",
      close: "Cerrar",
      back: "Volver",
      next: "Siguiente",
      continue: "Continuar",
      finally: "Finalizar",
      search: "Buscar",
      reset: "Restablecer",
      clear: "Limpiar",
      refresh: "Actualizar",
      filter: "Filtrar",
      show: "Mostrar",
      hide: "Ocultar",
      select: "Seleccionar",
      deselect: "Deseleccionar",
      upload: "Cargar",
      download: "Descargar",
      copy: "Copiar",
      paste: "Pegar",
      cut: "Cortar",
      clone: "Clonar",
      export: "Exportar",
      import: "Importar",
      selectAll: "Seleccionar todo",
      deselectAll: "Deseleccionar todo",
      more: "Más",
      readMore: "Leer más",
      info: "Información",
    },
    labels: {
      name: "Nombre",
      email: "Correo electrónico",
      phone: "Teléfono",
      date: "Fecha",
      time: "Hora",
      dateTime: "Fecha y hora",
      createdAt: "Creado en",
      updatedAt: "Actualizado en",
      status: "Estado",
      active: "Activo",
      inactive: "Inactivo",
      disabled: "Deshabilitado",
      info: "Información",
      statuses: {
        pending: "Pendiente",
        confirmed: "Confirmado",
        cancelled: "Cancelado",
        rejected: "Rechazado",
        created: "Creado",
      },
      loading: "Cargando",
      loadingRowsTable: "Cargando filas...",
      actions: "Acciones",
      action: "Acción",
      noData: "No hay datos",
      deleteMessage: "¿Estás seguro que deseas eliminar este registro?",
      deleteMessageTitle: "Eliminar registro",
      deleteMessageId: "¿Estás seguro que deseas eliminar el registro con ID: ",
    },
  },
  toast: {
    success_add: "El registro se dió de alta correctamente.",
    success_edit: "El registro se modificó correctamente.",
    success_delete: "El registro se eliminó correctamente.",
    error_add: "Ocurrió un error al intentar agregar el registro.",
    error_edit: "Ocurrió un error al editar el registro.",
    error_delete: "Ocurrió un error al eliminar el registro.",
    copy: "Copiado al portapales!",
    title_error: "Error",
    title_success: "Exito",
    error_location: "Error al obtener la ubicación",
    error_location_message:
      "No se pudo obtener la ubicación, por favor intenta de nuevo.",
    error_update: "Ha ocurrido un error al actualizar la información",
    error: "Ha ocurrido un error",
    error_publish: "Ha ocurrido un error al publicar el servicio",
    error_get: "Ha ocurrido un error al obtener la información",
    error_update_service: "Ha ocurrido un error al actualizar el servicio",
    error_update_profile: "Ha ocurrido un error al actualizar el perfil",
    error_update_password: "Ha ocurrido un error al actualizar la contraseña",
    error_insert: "Ha ocurrido un error al guardar los datos",
    error_insert_service:
      "Ha ocurrido un error al intentar guardar el servicio",
    error_insert_profile: "Ha ocurrido un error al intentar guardar el perfil",
    error_links: "El link al que intenta acceder no existe o no es válido",
    error_load_services: "Ha ocurrido un error al cargar los servicios",
    error_load_profile: "Ha ocurrido un error al cargar el perfil",
    error_load_meetings: "Ha ocurrido un error al cargar las reuniones",
    error_load_notifications:
      "Ha ocurrido un error al cargar las notificaciones",
    error_load_feedbacks: "Ha ocurrido un error al cargar los feedbacks",
    error_permission:
      "No tienes permisos para realizar esta acción o ha ocurrido un error",
    error_validate: "Ha ocurrido un error al validar la información",
    error_checkout: "Ha ocurrido un error al contratar un servicio",
    error_load_data: "Ha ocurrido un error al cargar los datos.",
    permission_camera_denied: "Permiso de cámara denegado",
    permission_camera_bloqued: "Permiso de cámara bloqueado",
    permission_camera_denied_message:
      "Para poder usar la cámara, debes aceptar los permisos.",
    permission_camera_bloqued_message:
      "Permiso de cámara bloqueado, para acceder a la camara deberas habilitar el permiso desde la configuración de aplicaciones",
    permission_camera_limited:
      "La camara no esta disponible en este dispositivo",
    permission_location_denied: "Permiso de ubicación denegado",
    permission_location_denied_message:
      "Para poder usar la ubicación, debes aceptar los permisos.",
    permission_location_bloqued:
      "Permiso de ubicación bloqueado, para acceder a la ubicación deberas habilitar el permiso desde la configuración de aplicaciones",
    success_publish: "El servicio se publicó correctamente",
    success_update: "Tus datos fueron actualizados correctamente",
    success_update_service: "El servicio se actualizó correctamente",
    success_update_profile: "El perfil se actualizó correctamente",
    success_update_password: "La contraseña se actualizó correctamente",
    success_insert: "Los datos se guardaron correctamente",
    success_insert_service: "El servicio se guardó correctamente",
    success_delete_user: "La cuenta fue eliminada correctamente",
  },
  modules: {
    home: "Inicio",
    buttons: "Botones",
    cards: "Tarjetas",
    forms: "Formularios",
    tables: "Tablas",
    charts: "Gráficos",
    modals: "Modales",
    users: "Usuarios",
    user: "Usuario",
    organism: "Organismo",
    organisms: "Organismos",
    logs: "Logs",
    log: "Log",
    systems: "Sistemas",
    system: "Sistema",
    techs: "Técnologías",
    tech: "Técnología",
  },
  users: {
    title: "Usuarios",
    view: "Ver usuarios",
    dataUser: "Datos del usuario",
    dataPersonal: "Datos personales",
    form: {
      name: "Nombre",
      lastName: "Apellido",
      email: "Email",
      cuil: "Cuil",
      password: "Contraseña",
      confirmPassword: "Confirmar contraseña",
      phone: "Teléfono",
      role: "Rol",
      lastConnection: "Última conexión",
      enabled: "Habilitado",
      organism: "Organismo",
      system: "Sistema",
    },
  },
  device: {
    title: "Dispositivos",
    view: "Ver dispositivos",
  },
  systems: {
    title: "Sistemas",
    view: "Ver sistemas",
    enabledSystems: "Sistemas habilitados",
    form: {
      systemId: "ID del sistema",
      systemName: "Nombre del sistema",
      font: "Fuente",
      codeClientId: "ID de cliente",
      codeClientSecret: "Código secreto del cliente",
    },
    validations: {
      systemName: "El nombre del sistema es requerido",
      font: "La fuente es requerida",
    },
    messages: {
      error_system: "Ha ocurrido un error al intentar guardar el sistema",
      error_system_update:
        "Ha ocurrido un error al intentar actualizar el sistema",
    },
  },
  institution: {
    title: "Organismos",
    view: "Ver organismos",
    dataOrganism: "Datos del organismo",
    form: {
      organism: "Organismo",
      description: "Descripción",
    },
    validations: {
      organism: "El organismo es requerido",
      description: "La descripción es requerida",
    },
    messages: {
      error_organism: "Ha ocurrido un error al intentar guardar el organismo",
      error_organism_update:
        "Ha ocurrido un error al intentar actualizar el organismo",
    },
  },
  logs: {
    title: "Logs",
    view: "Ver logs",
    form: {
      date: "Fecha",
      publicIp: "IP pública",
      category: "Categoría",
      system: "Sistema",
      description: "Descripción",
    },
  },
  tech: {
    title: "Tecnologías",
    view: "Ver tecnologías",
    form: {
      name: "Nombre",
      tech: "Tecnología",
      description: "Descripción",
    },
    validations: {
      name: "El nombre es requerido",
    },
    messages: {
      error_tech: "Ha ocurrido un error al intentar guardar la tecnología",
      error_tech_update:
        "Ha ocurrido un error al intentar actualizar la tecnología",
    },
  },
  login: {
    common: {
      welcome_message: "¡Bienvenido a Admin-auth! 👋🏻",
    },
    form: {
      usuario: "Nombre de Usuario",
      password: "Contraseña",
      labelCuil: "Ingrese su Nombre de usuario",
    },
    messages: {
      loginToNext: "Inicie sesión en su cuenta y comience la aventura",
      successLogin: "Sesión iniciada correctamente",
      successLogout: "Sesion cerrada",
      errorLogin: "Ha ocurrido un error al iniciar sesión",
      verifyCredentials: "Verifique sus credenciales",
      errorRegister: "Ha ocurrido un error al intentar registrarse",
    },
  },
  newsletter: {
    form: {
      fieldTitle: "Titulo",
      title: {
        fieldTitle: "Titulo",
        fieldName: "title",
      }

    }
  },
  ActionsType: {
    title: "Tipos de Acciones",
    subTitle: "Tipos de Acciones de los modúlos",
    new: "Nuevo tipo de Acción",
    edit: "Editar tipo de Acción",
    detail: "Detalle del tipo de Acción",
    list: "Lista de tipos de secciones",
    form: {
      name: "Nombre",
      description: "Descripción",
    },
    validation: {
      nameIsRequired: "El nombre es requerido",
      descriptionIsRequired: "La descripción es requerida",
    },
    messages: {
      createdSuccess: "El tipo de acción se creó correctamente",
      updatedSuccess: "El tipo de acción se actualizó correctamente",
      deletedSuccess: "El tipo de acción se eliminó correctamente",
      createdError: "Error al crear el tipo de acción",
      updatedError: "Error al actualizar el tipo de acción",
      deletedError: "Error al eliminar el tipo de acción",
    },
  },

  IvaType: {
    title: "Tipos de Iva",
    subTitle: "Tipos de Iva de los modúlos",
    new: "Nuevo tipo de Iva",
    edit: "Editar tipo de Iva",
    detail: "Detalle del tipo de Iva ",
    list: "Lista de tipos de Iva",
    form: {
      description: "Descripcion",
      percent: "Porcentaje",
    },
    validation: {
      descriptionIsRequired: "La description es requerida",
      percentIsRequired: "El porcentaje es requerido",
    },
    messages: {
      createdSuccess: "El tipo de Iva se creó correctamente",
      updatedSuccess: "El tipo de Iva se actualizó correctamente",
      deletedSuccess: "El tipo de Iva se eliminó correctamente",
      createdError: "Error al crear el tipo de Iva",
      updatedError: "Error al actualizar el tipo de Iva",
      deletedError: "Error al eliminar el tipo de Iva",
    },
  },
  MarcaType: {
    title: "Tipos de Marca",
    subTitle: "Tipos de Marca de los modúlos",
    new: "Nuevo tipo de Marca",
    edit: "Editar tipo de Marca",
    detail: "Detalle del tipo de Marca",
    list: "Lista de tipos de secciones",
    form: {
      name: "Nombre",
    },
    validation: {
      nameIsRequired: "El nombre es requerido",
    },
    messages: {
      createdSuccess: "El tipo de Marca se creó correctamente",
      updatedSuccess: "El tipo de Marca se actualizó correctamente",
      deletedSuccess: "El tipo de Marca se eliminó correctamente",
      createdError: "Error al crear el tipo de Marca",
      updatedError: "Error al actualizar el tipo de Marca",
      deletedError: "Error al eliminar el tipo de Marca",

    },
  },
  System: {
    title: "Sistemas",
    subTitle: "Sistemas Hablitidaos",
    new: "Nuevo Sistema",
    edit: "Editar Sistema",
    detail: "Detalle del Sistema",
    list: "Lista de Sistema",
    form: {
      name: "Nombre",
      description: "Descripción",
      url: "URL",
      icono: "Icono"
    },
    validation: {
      nameIsRequired: "El nombre es requerido",
    },
    messages: {
      createdSuccess: "El Sistema se creó correctamente",
      updatedSuccess: "El Sistema se actualizó correctamente",
      deletedSuccess: "El Sistema se eliminó correctamente",
      createdError: "Error al crear el Sistema",
      updatedError: "Error al actualizar el Sistema",
      deletedError: "Error al eliminar el Sistema",

    },
  },
  Organization: {
    title: "Organización",
    subTitle: "Organizaciones Hablitidas",
    new: "Nueva Organización",
    edit: "Editar Organización",
    detail: "Detalle de la Organización",
    list: "Lista de Organizaciones",
    form: {
      name: "Nombre",
      dataBase: "Nombre De la Base de datos",
      host: "Host",
      port: "Puerto",
      user: "Usuario",
      password: "Contraseña",
      tipoBD: "Tipo de Base de Datos",
    },
    validation: {
      nameIsRequired: "El nombre es Requerido.",
      dataBaseIsRequired: "El nombre de la Base de Datos es Requerido.",
      hostIsRequired: "El Host es Requerido.",
      portIsRequired: "El Puerto es Requerido.",
      userIsRequired: "El Usuario es Requerido.",
      passwordIsRequired: "La contraseña es Requerida.",
      tipoBDIsRequired: "El tipo de la Base de Datos es Requerido.",
    },
    messages: {
      createdSuccess: "La Organización se creó correctamente.",
      updatedSuccess: "La Organización se actualizó correctamente.",
      deletedSuccess: "La Organización se eliminó correctamente.",
      createdError: "Error al crear la Organización.",
      updatedError: "Error al actualizar la Organización.",
      deletedError: "Error al eliminar la Organización.",

    },
  },
  PresentacionType: {
    title: "Tipos de Presentacion.",
    subTitle: "Tipos de Presentacion",
    new: "Nuevo tipo de Presentacion",
    edit: "Editar tipo de Presentacion",
    detail: "Detalle del tipo de Presentaciona",
    list: "Lista de tipos de secciones",
    form: {
      name: "Nombre",
      acronym: "Siglas",

    },
    validation: {
      nameIsRequired: "El nombre es requerido",
      acronymIsRequired: "Las siglas son requridas",
      nameMinLength: "Minima longitud 3 caracteres",
      nameUppercase: "El nombre tiene que estar en mayusculas",

    },
    messages: {
      createdSuccess: "La Presentacion se creó correctamente",
      updatedSuccess: "La Presentacion se actualizó correctamente",
      deletedSuccess: "La Presentacion se eliminó correctamente",
      createdError: "Error al crear la Presentacion",
      updatedError: "Error al actualizar la Presentacion",
      deletedError: "Error al eliminar la Presentacion",
    },
  },
  Suscripcion: {
    title: "Suscripción",
    subTitle: "Suscripciones Hablitidas",
    new: "Nueva Suscripción",
    edit: "Editar Suscripción",
    detail: "Detalle de la Suscripción",
    list: "Lista de Suscripciones",
    form: {
      name: "Nombre",
      description: "Descripción",
      system: "Sistema",
    },
    validation: {
      nameIsRequired: "El nombre es requerido",
      descriptionIsRequired: "La descripción es requerida",
      systemIsRequired: "El sistema es requerido",
    },
    messages: {
      createdSuccess: "La Suscripción se creó correctamente",
      updatedSuccess: "La Suscripción se actualizó correctamente",
      deletedSuccess: "La Suscripción se eliminó correctamente",
      createdError: "Error al crear la Suscripción",
      updatedError: "Error al actualizar la Suscripción",
      deletedError: "Error al eliminar la Suscripción",
    },
  },
  User: {
    title: "Usuario",
    subTitle: "Usuarios Habilitados",
    new: "Nuevo Usuario",
    edit: "Editar Usuario",
    detail: "Detalle del Usuario",
    list: "Lista de Usuarios",
    form: {
      name: "Nombre de Usuario",
      email: "E-Mail",
      password: "Contraseña",
      repeatPassword: "Repeteir Contraseña",
    },
    validation: {
      nameIsRequired: "El nombre es requerido",
      descriptionIsRequired: "La descripción es requerida",
      systemIsRequired: "El sistema es requerido",
    },
    messages: {
      createdSuccess: "El Usuario se creó correctamente",
      updatedSuccess: "El Usuario se actualizó correctamente",
      deletedSuccess: "El Usuario se eliminó correctamente",
      createdError: "Error al crear el Usuario",
      updatedError: "Error al actualizar el Usuario",
      deletedError: "Error al eliminar el Usuario",
      deletedConfirm: "Esta seguro que desea eliminar este registro?",
    }
  }
};
