export const es_ar = {
  system: {
    name: "Admin-Landing",
  },
  common: {
    welcome: "Bienvenido",
    appName: "Admin Landing",
    messageWelcome: "Bienvenido al sistema de gestion de Landing",
    actions: {
      detail: "Detalles",
      edit: "Editar",
      delete: "Eliminar",
      view: "Ver",
      cancel: "Cancelar",
      save: "Guardar",
      create: "Crear",
      confirm: "Confirmar",
      add: "Agregar",
      new: "Nuevo",
      remove: "Remover",
      accept: "Aceptar",
      reject: "Rechazar",
      enter: "Ingresar",
      open: "Abrir",
      close: "Cerrar",
      back: "Volver",
      next: "Siguiente",
      continue: "Continuar",
      finally: "Finalizar",
      search: "Buscar",
      reset: "Restablecer",
      clear: "Limpiar",
      refresh: "Actualizar",
      filter: "Filtrar",
      show: "Mostrar",
      hide: "Ocultar",
      select: "Seleccionar",
      deselect: "Deseleccionar",
      upload: "Cargar",
      download: "Descargar",
      copy: "Copiar",
      paste: "Pegar",
      cut: "Cortar",
      clone: "Clonar",
      export: "Exportar",
      import: "Importar",
      selectAll: "Seleccionar todo",
      deselectAll: "Deseleccionar todo",
      more: "Más",
      readMore: "Leer más",
      info: "Información",
    },
    labels: {
      name: "Nombre",
      email: "Correo electrónico",
      phone: "Teléfono",
      date: "Fecha",
      time: "Hora",
      dateTime: "Fecha y hora",
      createdAt: "Creado en",
      updatedAt: "Actualizado en",
      status: "Estado",
      active: "Activo",
      inactive: "Inactivo",
      disabled: "Deshabilitado",
      info: "Información",
      statuses: {
        pending: "Pendiente",
        confirmed: "Confirmado",
        cancelled: "Cancelado",
        rejected: "Rechazado",
        created: "Creado",
      },
      loading: "Cargando",
      loadingRowsTable: "Cargando filas...",
      actions: "Acciones",
      action: "Acción",
      noData: "No hay datos",
      deleteMessage: "¿Estás seguro que deseas eliminar este registro?",
      deleteMessageTitle: "Eliminar registro",
      deleteMessageId: "¿Estás seguro que deseas eliminar el registro con ID: ",
    },
    validationString: {
      noEmptySpaces: "El campo no puede contener solo espacios en blanco",
      noLeadingSpaces: "El campo no puede tener espacios en blanco al inicio",
      noTrailingSpaces: "El campo no puede tener espacios en blanco al final",
      fieldRequired: "El campo es obligatorio",
      minLength: "El campo debe tener al menos {{min}} caracteres",
      maxLength: "El campo debe tener como máximo {{max}} caracteres",
      exactLength: "El campo debe tener exactamente {{exactLength}} caracteres",
      invalidEmail: "El campo debe ser un correo electrónico válido",
      invalidUrl: "El campo debe ser una URL válida",
      patternMismatch: "El campo no coincide con el patrón",
      mustBeUppercase: "El campo debe estar en mayúsculas",
      mustBeLowercase: "El campo debe estar en minúsculas",
      mustBeOneOf: "El campo debe ser uno de los siguientes valores: ",
      cannotBeOneOf: "El campo no puede ser uno de los siguientes valores: ",
      allowSpecialChars: "El campo no puede contener caracteres especiales",
      allowNumericOnly: "El campo debe contener solo números",
      invalidPhone: "El campo debe ser un número de teléfono válido",
      numericOnly: "El campo debe contener solo números",
      invalidDate: "La fecha debe ser válida",
      invalidImage: "Debe ser una imagen valida (jpg|jpeg|png|bmp|webp)",
    },
    validationNumber: {
      mustBePositive: "El campo debe ser un número positivo",
      mustBeNegative: "El campo debe ser un número negativo",
      minValue: "El campo debe ser mayor o igual a ",
      maxValue: "El campo debe ser menor o igual a ",
      lessThan: "El campo debe ser menor que ",
      moreThan: "El campo debe ser mayor que ",
      precision: "El campo debe contener {{precision}} decimales",
      mustBeInteger: "El campo debe ser un número entero",
      cannotBeZero: "El campo no puede ser cero",
      mustBeMultipleOf: "El campo debe ser un múltiplo de ",
      mustBeInRange: "El campo debe estar en el rango de ",
      invalidDecimalSeparator: "El campo debe tener un separador decimal válido",
      invalidThousandSeparator: "El campo debe tener un separador de miles válido",
    },
    errors: {
      createdError: "Error al crear",
      unknownError: "Error desconocido"
    }
  },
  toast: {
    success_add: "El registro se dió de alta correctamente.",
    success_edit: "El registro se modificó correctamente.",
    success_delete: "El registro se eliminó correctamente.",
    error_add: "Ocurrió un error al intentar agregar el registro.",
    error_edit: "Ocurrió un error al editar el registro.",
    error_delete: "Ocurrió un error al eliminar el registro.",
    copy: "Copiado al portapales!",
    title_error: "Error",
    title_success: "Exito",
    error_location: "Error al obtener la ubicación",
    error_location_message:
      "No se pudo obtener la ubicación, por favor intenta de nuevo.",
    error_update: "Ha ocurrido un error al actualizar la información",
    error: "Ha ocurrido un error",
    error_publish: "Ha ocurrido un error al publicar el servicio",
    error_get: "Ha ocurrido un error al obtener la información",
    error_update_service: "Ha ocurrido un error al actualizar el servicio",
    error_update_profile: "Ha ocurrido un error al actualizar el perfil",
    error_update_password: "Ha ocurrido un error al actualizar la contraseña",
    error_insert: "Ha ocurrido un error al guardar los datos",
    error_insert_service:
      "Ha ocurrido un error al intentar guardar el servicio",
    error_insert_profile: "Ha ocurrido un error al intentar guardar el perfil",
    error_links: "El link al que intenta acceder no existe o no es válido",
    error_load_services: "Ha ocurrido un error al cargar los servicios",
    error_load_profile: "Ha ocurrido un error al cargar el perfil",
    error_load_meetings: "Ha ocurrido un error al cargar las reuniones",
    error_load_notifications:
      "Ha ocurrido un error al cargar las notificaciones",
    error_load_feedbacks: "Ha ocurrido un error al cargar los feedbacks",
    error_permission:
      "No tienes permisos para realizar esta acción o ha ocurrido un error",
    error_validate: "Ha ocurrido un error al validar la información",
    error_checkout: "Ha ocurrido un error al contratar un servicio",
    error_load_data: "Ha ocurrido un error al cargar los datos.",
    permission_camera_denied: "Permiso de cámara denegado",
    permission_camera_bloqued: "Permiso de cámara bloqueado",
    permission_camera_denied_message:
      "Para poder usar la cámara, debes aceptar los permisos.",
    permission_camera_bloqued_message:
      "Permiso de cámara bloqueado, para acceder a la camara deberas habilitar el permiso desde la configuración de aplicaciones",
    permission_camera_limited:
      "La camara no esta disponible en este dispositivo",
    permission_location_denied: "Permiso de ubicación denegado",
    permission_location_denied_message:
      "Para poder usar la ubicación, debes aceptar los permisos.",
    permission_location_bloqued:
      "Permiso de ubicación bloqueado, para acceder a la ubicación deberas habilitar el permiso desde la configuración de aplicaciones",
    success_publish: "El servicio se publicó correctamente",
    success_update: "Tus datos fueron actualizados correctamente",
    success_update_service: "El servicio se actualizó correctamente",
    success_update_profile: "El perfil se actualizó correctamente",
    success_update_password: "La contraseña se actualizó correctamente",
    success_insert: "Los datos se guardaron correctamente",
    success_insert_service: "El servicio se guardó correctamente",
    success_delete_user: "La cuenta fue eliminada correctamente",
  },
  modules: {
    home: "Inicio",
    buttons: "Botones",
    cards: "Tarjetas",
    forms: "Formularios",
    tables: "Tablas",
    charts: "Gráficos",
    modals: "Modales",
    users: "Usuarios",
    user: "Usuario",
    organism: "Organismo",
    organisms: "Organismos",
    logs: "Logs",
    log: "Log",
    systems: "Sistemas",
    system: "Sistema",
    techs: "Técnologías",
    tech: "Técnología",
  },
  users: {
    title: "Usuarios",
    view: "Ver usuarios",
    dataUser: "Datos del usuario",
    dataPersonal: "Datos personales",
    form: {
      name: "Nombre",
      lastName: "Apellido",
      email: "Email",
      cuil: "Cuil",
      password: "Contraseña",
      confirmPassword: "Confirmar contraseña",
      phone: "Teléfono",
      role: "Rol",
      lastConnection: "Última conexión",
      enabled: "Habilitado",
      organism: "Organismo",
      system: "Sistema",
    },
  },
  device: {
    title: "Dispositivos",
    view: "Ver dispositivos",
  },
  systems: {
    title: "Sistemas",
    view: "Ver sistemas",
    enabledSystems: "Sistemas habilitados",
    form: {
      systemId: "ID del sistema",
      systemName: "Nombre del sistema",
      font: "Fuente",
      codeClientId: "ID de cliente",
      codeClientSecret: "Código secreto del cliente",
    },
    validations: {
      systemName: "El nombre del sistema es obligatorio",
      font: "La fuente es obligatoria",
    },
    messages: {
      error_system: "Ha ocurrido un error al intentar guardar el sistema",
      error_system_update:
        "Ha ocurrido un error al intentar actualizar el sistema",
    },
  },
  institution: {
    title: "Organismos",
    view: "Ver organismos",
    dataOrganism: "Datos del organismo",
    form: {
      organism: "Organismo",
      description: "Descripción",
    },
    validations: {
      organism: "El organismo es obligatorio",
      description: "La descripción es obligatoria",
    },
    messages: {
      error_organism: "Ha ocurrido un error al intentar guardar el organismo",
      error_organism_update:
        "Ha ocurrido un error al intentar actualizar el organismo",
    },
  },
  logs: {
    title: "Logs",
    view: "Ver logs",
    form: {
      date: "Fecha",
      publicIp: "IP pública",
      category: "Categoría",
      system: "Sistema",
      description: "Descripción",
    },
  },
  tech: {
    title: "Tecnologías",
    view: "Ver tecnologías",
    form: {
      name: "Nombre",
      tech: "Tecnología",
      description: "Descripción",
    },
    validations: {
      name: "El nombre es obligatorio",
    },
    messages: {
      error_tech: "Ha ocurrido un error al intentar guardar la tecnología",
      error_tech_update:
        "Ha ocurrido un error al intentar actualizar la tecnología",
    },
  },
  login: {
    common: {
      welcome_message: "¡Bienvenido a Admin-Landing! 👋🏻",
    },
    form: {
      usuario: "Nombre de Usuario",
      password: "Contraseña",
      labelCuil: "Ingrese su Nombre de usuario",
    },
    messages: {
      loginToNext: "Inicie sesión en su cuenta y comience la aventura",
      successLogin: "Sesión iniciada correctamente",
      successLogout: "Sesion cerrada",
      errorLogin: "Ha ocurrido un error al iniciar sesión",
      verifyCredentials: "Verifique sus credenciales",
      errorRegister: "Ha ocurrido un error al intentar registrarse",
      loginSuccess: "Se inicio sesion Correctamente!",
      loginError: "No se pudo iniciar sesion",

    },
  },
  organizacion: {
    title: "Organizaciones",
    subTitle: "Listado de Organizaciones",
    new: "Nueva Organización",
    edit: "Editar Organización",
    detail: "Detalle de la Organización",
    list: "Lista de Organizaciones",
    form: {
      nombre: "Nombre",

    },
    validation: {
      nombreIsRequired: "El nombre es requerido",
    },
    messages: {
      createdSuccess: "El Registro se creó correctamente",
      updatedSuccess: "El Registro se actualizó correctamente",
      deletedSuccess: "El Registro se eliminó correctamente",
      createdError: "Error al crear el Registro",
      updatedError: "Error al actualizar el Registro",
      deletedError: "Error al eliminar el Registro",
      deletedConfirm: "Esta seguro que desea eliminar el registro?",
    },
  },
  sistemas: {
    title: "Sistemas",
    subTitle: "Listado de Sistemas",
    new: "Nuevo Sistema",
    edit: "Editar Sistema",
    detail: "Detalle del Sistema",
    list: "Lista de Sistemas",
    form: {
      nombre: "Nombre del Sistema",
      descripcion: "Descripción del sistema",
      url: "Url del sistema",
      icon: "Icono del sistema",
      host: "Host de la base de datos",
      port: "Puerto de la base de datos",
      usuario: "Usuario de la base de datos",
      password: "Contraseña de la base de datos",
      tipobd: "Tipo de base de datos del sistema"
    },
    validation: {
      nameIsRequired: "El nombre es requerido",
      descriptionIsRequired: "La descripción es requerida",
      urlIsRequired: "El url es requerido",
      iconIsRequired: "El icono es requerido",
      hostIsRequired: "El host es requerido",
      portIsRequired: "El puerto es requerido",
      usuarioIsRequired: "El usuario es requerido",
      passwordIsRequired: "La contraseña es requerida",
      tipobdIsRequired: "El tipo de base de datos es requerido",
    },
    messages: {
      createdSuccess: "El Registro se creó correctamente",
      updatedSuccess: "El Registro se actualizó correctamente",
      deletedSuccess: "El Registro se eliminó correctamente",
      createdError: "Error al crear el Registro",
      updatedError: "Error al actualizar el Registro",
      deletedError: "Error al eliminar el Registro",
      deletedConfirm: "Esta seguro que desea eliminar el registro?",
    },
  },
  suscripcion: {
    title: "Suscripciones",
    subTitle: "Listado de Suscripciones",
    new: "Nueva Suscripción",
    edit: "Editar Suscripción",
    detail: "Detalle del Suscripción",
    list: "Lista de Suscripciones",
    form: {
      nombre: "Nombre de la Suscripción",
      descripcion: "Descripción de la Suscripción",
      sistema: "Sistema la que pertenece",
    },
    validation: {
      nombreIsRequired: "El nombre es requerido",
      descripcionIsRequired: "La descripción es requerida",
      sistemaIsRequired: "El sistema es requerido",
    },
    messages: {
      createdSuccess: "El Registro se creó correctamente",
      updatedSuccess: "El Registro se actualizó correctamente",
      deletedSuccess: "El Registro se eliminó correctamente",
      createdError: "Error al crear el Registro",
      updatedError: "Error al actualizar el Registro",
      deletedError: "Error al eliminar el Registro",
      deletedConfirm: "Esta seguro que desea eliminar el registro?",
    },
  },
  plan: {
    title: "Planes",
    subTitle: "Listado de Planes",
    new: "Nuevo Plan",
    edit: "Editar Plan",
    detail: "Detalle del Plan",
    list: "Lista de Planes",
    form: {
      nombre: "Nombre del Plan",
      descripcion: "Descripción del Plan",
      suscripcion: "Suscripción a la que pertenece",
      duracion: "Duración en Días",
      precio: "Precio",
    },
    validation: {
      nombreIsRequired: "El nombre es requerido",
      descripcionIsRequired: "La descripción es requerida",
      suscripcionIsRequired: "La suscripción es requerida",
      duracionIsRequired: "La duración es requerida",
      precioIsRequired: "El precio es requerido",
    },
    messages: {
      createdSuccess: "El Registro se creó correctamente",
      updatedSuccess: "El Registro se actualizó correctamente",
      deletedSuccess: "El Registro se eliminó correctamente",
      createdError: "Error al crear el Registro",
      updatedError: "Error al actualizar el Registro",
      deletedError: "Error al eliminar el Registro",
      deletedConfirm: "Esta seguro que desea eliminar el registro?",
    },
  },

  accion: {
    title: "Acciones",
    subTitle: "Listado de Acciones",
    new: "Nueva Acción",
    edit: "Editar Acción",
    detail: "Detalle del Acción",
    list: "Lista de Acciones",
    form: {
      nombre: "Nombre de la Acción",
      descripcion: "Sigla de la Acción",
    },
    validation: {
      nombreIsRequired: "El nombre es requerido",
      descripcionIsRequired: "La sigla es requerida",
    },
    messages: {
      createdSuccess: "El Registro se creó correctamente",
      updatedSuccess: "El Registro se actualizó correctamente",
      deletedSuccess: "El Registro se eliminó correctamente",
      createdError: "Error al crear el Registro",
      updatedError: "Error al actualizar el Registro",
      deletedError: "Error al eliminar el Registro",
      deletedConfirm: "Esta seguro que desea eliminar el registro?",
    },
  },
  contrato: {
    title: "Contratos",
    subTitle: "Listado de Contratos",
    new: "Nuevo Contrato",
    edit: "Editar Contrato",
    detail: "Detalle del Contrato",
    list: "Lista de Contratos",
    form: {
      plan: "Plan a contratar",
      organizacion: "Organización",
      fechaVencimiento: "Fecha De expiración",
    },
    validation: {
      planIsRequired: "El el plan es requerido",
      organizacionIsRequired: "La organización es requerida",
      fechaVencimientoIsRequired: "La fecha de expiración es requerida",
    },
    messages: {
      createdSuccess: "El Registro se creó correctamente",
      updatedSuccess: "El Registro se actualizó correctamente",
      deletedSuccess: "El Registro se eliminó correctamente",
      createdError: "Error al crear el Registro",
      updatedError: "Error al actualizar el Registro",
      deletedError: "Error al eliminar el Registro",
      deletedConfirm: "Esta seguro que desea eliminar el registro?",
    },
  },
  persona: {
    title: "Personas",
    subTitle: "Listado de Personas",
    new: "Nueva Persona",
    edit: "Editar Persona",
    detail: "Detalle de la perosna",
    list: "Lista de Personas",
    form: {
      nombre: "Nombre",
      apellido: "Apellido",
      cuil: "Cuil",
      genero: "Genero"

    },
    validation: {
      nameIsRequired: "El nombre es requerido",
      lastNameIsRequired: "El apellido es requerido",
      genderIsRequired: "El genero es requerido",
      cuilIsRequired: "El cuil es requerido",
      cuilMustBeNumber: "El cuil debe ser un numero",
      cuilMustBePositive: "El cuil debe ser un numero positivo",
      cuilMustBeInteger: "El cuil debe ser un numero entero",
      cuilMaxLength: "El cuild debe tener como maximo 11 caracteres",
      invalidGender: "El genero seleccionado no esta entre las opciones",
      cuilInvalid: "El cuil no es valido"
    },
    messages: {
      createdSuccess: "El Registro se creó correctamente",
      updatedSuccess: "El Registro se actualizó correctamente",
      deletedSuccess: "El Registro se eliminó correctamente",
      createdError: "Error al crear el Registro",
      updatedError: "Error al actualizar el Registro",
      deletedError: "Error al eliminar el Registro",
      deletedConfirm: "Esta seguro que desea eliminar el registro?",
    },
  },
  usuario: {
    title: "Usuarios",
    subTitle: "Listado de Usuarios",
    new: "Nueva Usuario",
    edit: "Editar Usuario",
    detail: "Detalle de la usuario",
    list: "Lista de Usuarios",
    form: {
      nombre: "Nombre de usuario",
      email: "Email",
      password: "Contraseña",
      repeatPassword: "Repetir Contraseña",
      persona: "Persona"
    },
    validation: {
      nameIsRequired: "El nombre es requerido",
      emailIsRequired: "El email es requerido",
      passwordIsRequired: "La contraseña es requerida",
      repeatPasswordIsRequired: "Se debe repetir la contraseña",
      personIsRequired: "La persona es requerida",
    },
    messages: {
      createdSuccess: "El Registro se creó correctamente",
      updatedSuccess: "El Registro se actualizó correctamente",
      deletedSuccess: "El Registro se eliminó correctamente",
      createdError: "Error al crear el Registro",
      updatedError: "Error al actualizar el Registro",
      deletedError: "Error al eliminar el Registro",
      deletedConfirm: "Esta seguro que desea eliminar el registro?",
    },
  },
  modulo: {
    title: "Módulos",
    subTitle: "Listado de Módulos",
    new: "Nuevo Módulo",
    edit: "Editar Módulo",
    detail: "Detalle del Módulo",
    list: "Lista de Módulos",
    form: {
      nombre: "Nombre del Módulo",
      descripcion: "Descripción",
      label: "Label",
      element: "Elemento",
      icon: "Icono",
      path: "Path",
      moduloPadre: "Módulo Padre",
      sistema: "Sistema",
      accionesPorModulo: "Acciones por Módulo"
    },
    validation: {
      nombreIsRequired: "El nombre es requerido",
      descripcionIsRequired: "La descripción es requerida",
      labelIsRequired: "El label es requerido",
      elementIsRequired: "El elemento es requerido",
      iconIsRequired: "El icono es requerido",
      pathIsRequired: "El path es requerido",
      sistemaIsRequired: "El sistema es requerido",
      accionesPorModuloIsRequired: "Debe seleccionar al menos una acción"
    },
    messages: {
      createdSuccess: "El Registro se creó correctamente",
      updatedSuccess: "El Registro se actualizó correctamente",
      deletedSuccess: "El Registro se eliminó correctamente",
      createdError: "Error al crear el Registro",
      updatedError: "Error al actualizar el Registro",
      deletedError: "Error al eliminar el Registro",
      deletedConfirm: "¿Está seguro que desea eliminar el registro?"
    }
  },
  accionModulo: {
    title: "Acción Por Modulo",
    subTitle: "Listado de Acciones Por Modulos",
    new: "Nueva Acción Por Modulo",
    edit: "Editar Acción Por Modulo",
    detail: "Detalle de las Acciones Por Modulos",
    list: "Lista de Acciones Por Modulos",
    form: {
      module: "Nombre de Modulos",
      acction: "Acción",

    },
    validation: {
      moduleIsRequired: "El modulo es requerido",
      acctionIsRequired: "La acción es requerida",
      moduleMustBeDifferentFromZero: "Debe seleccionar un modulo",
      acctionMustBeDifferentFromZero: "Debe seleccionar una acción",
    },
    messages: {
      createdSuccess: "El Registro se creó correctamente",
      updatedSuccess: "El Registro se actualizó correctamente",
      deletedSuccess: "El Registro se eliminó correctamente",
      createdError: "Error al crear el Registro",
      updatedError: "Error al actualizar el Registro",
      deletedError: "Error al eliminar el Registro",
      deletedConfirm: "Esta seguro que desea eliminar el registro?",
    },
  },
  rol: {
    title: "Rol",
    subTitle: "Listado de Rol",
    new: "Nuevo Rol",
    edit: "Editar Rol",
    detail: "Detalle del Rol",
    list: "Lista de Rol",
    form: {
      name: "Nombre de Rol",
      description: "Descripción",
      system: "Sistema",
      module: "Modulo",
      acction: "Acción",
    },
    validation: {
      nameIsRequired: "El nombre es requerido",
      descriptionIsRequired: "La descripción es requerida",
    },
    messages: {
      createdSuccess: "El Registro se creó correctamente",
      updatedSuccess: "El Registro se actualizó correctamente",
      deletedSuccess: "El Registro se eliminó correctamente",
      createdError: "Error al crear el Registro",
      updatedError: "Error al actualizar el Registro",
      deletedError: "Error al eliminar el Registro",
      deletedConfirm: "Esta seguro que desea eliminar el registro?",
    },
  },
  accionRol: {
    title: "Acción Por Rol",
    subTitle: "Listado de Acciones Por Rol",
    new: "Nueva Acción Por Rol",
    edit: "Editar Acción Por Rol",
    detail: "Detalle de las Acciones Por Rol",
    list: "Lista de Acciones Por Rol",
    form: {
      rol: "Rol",
      acction: "Acción",
    },
    validation: {
      rolIsRequired: "El rol es requerido",
      acctionIsRequired: "La acción es requerida",
    },
    messages: {
      createdSuccess: "El Registro se creó correctamente",
      updatedSuccess: "El Registro se actualizó correctamente",
      deletedSuccess: "El Registro se eliminó correctamente",
      createdError: "Error al crear el Registro",
      updatedError: "Error al actualizar el Registro",
      deletedError: "Error al eliminar el Registro",
      deletedConfirm: "Esta seguro que desea eliminar el registro?",
    },
  },
  permisos: {
    title: "Permisos",
    subTitle: "Listado de Permisos",
    new: "Nuevo Permiso",
    edit: "Editar Permiso",
    detail: "Detalle del Permiso",
    list: "Lista de Permisos",
    form: {
      usuario: "Usuario",
      sistema: "Sistema",
      organizacion: "Organización",
      rol: "Rol",
    },
    validation: {
      userIsRequired: "El usuario es requerido",
      systemIsRequired: "El sistema es requerido",
      organizationIsRequired: "La organización es requerida",
      rolIsRequired: "El rol es requerido",
      userMustBeDifferentFromZero: "Debe seleccionar un usuario",
      systemMustBeDifferentFromZero: "Debe seleccionar un sistema",
      organizationMustBeDifferentFromZero: "Debe seleccionar una organización",
      rolMustBeDifferentFromZero: "Debe seleccionar un rol",
    },
    messages: {
      createdSuccess: "El Registro se creó correctamente",
      updatedSuccess: "El Registro se actualizó correctamente",
      deletedSuccess: "El Registro se eliminó correctamente",
      createdError: "Error al crear el Registro",
      updatedError: "Error al actualizar el Registro",
      deletedError: "Error al eliminar el Registro",
      deletedConfirm: "Esta seguro que desea eliminar el registro?",
    },
  }



};