export interface IAuthTokenReq {
    client_id: string | undefined;
    client_secret: string | undefined;
}

export interface IAuthTokenRes {
    token: string;
}

export type statusAuth = 'LOGGED' | 'NOT_LOGGED';

export interface IAuthLoginReq {
    cuil: string;
    password: string;
}

export interface IAuthLoginRes {
    accessToken: string;
    user: User;
}


export interface IErrorAuthLogin {
    statusCode: number;
    message: string;
}

export interface IErrorAuth {
    statusCode: number;
    message: string[];
    error: string;
}

export interface User {
    cuil: string;
    nombre: string;
    apellido: string;
    email: string;
    activo: boolean;  
    organismo: Organismo;
}

export interface Dispositivo {
    _id: string;
    appName: string;
    appVersion: string;
    codeName: string;
    cookieEnabled: string;
    lenguague: string;
    navOnline: string;
    plataform: string;
    userAgent: string;
}

export interface Organismo {
    sistema: string;
}

export interface IDPreform02 {
    _bsontype: string;
    id: ID;
}

export interface ID {
    type: string;
    data: number[];
}

export interface SistemasHabilitado {
    id: IDPreform02;
    id_system: string;
    system_name: string;
    fuente: string;
    client_id: string;
    client_secret: string;
}



// Generated by https://quicktype.io

export interface IResPAPI {
    accessToken: string;
    user:        User;
}

export interface User {
    cuil:     string;
    nombre:   string;
    apellido: string;
    email:    string;
    activo:   boolean;
    avatar:   string;
    sistema:  string;
}

